### ISSUE TITLE
How can I auto-generate types for a new API version? 

### ISSUE THREAD

**Issue by sherifnada** [facebook/facebook-business-sdk-codegen#48]
Is there a way to update the JSON defs for a new API version? for example currently, this package only support v14 but v15 is available. I would like to generate Python SDK code using this package so I can submit it downstream to resolve hard blockers like [this one](https://github.com/facebook/facebook-python-business-sdk/pull/620). However, I'm not sure how to autogenerate. I looked around the repo and didn't find something which can achieve this. Could you help? 

I guess more generally, as a consumer of this package, what are my options for staying up to date with API changes while still using an SDK generated by this package?

**Comment by sherifnada** [comment]
maybe @stcheng can help as one of the more recent contributors to this package?

**Comment by stcheng** [comment]
This is an internal procedure. We are targeting future releases to be released on time along with the GraphAPI version release. We are also trying to address the issue that SDK only supports the latest version.
